/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#F07A7A';
const tintColorDark = '#F07A7A';

export const Colors = {
  light: {
    text: '#1A1A1A',
    textSecondary: '#6B7280',
    background: '#F5F5F5',
    tint: tintColorLight,
    icon: '#6B7280',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: tintColorLight,
    primary: '#F07A7A',
    secondary: '#FFE5E5',
    card: '#FFFFFF',
    border: '#E5E7EB',
    buttonText: '#FFFFFF',
    buttonDisabled: '#cccccc',
    statusActive: '#10B981',
    statusNew: '#3B82F6',
    statusFading: '#F59E0B',
    statusEnded: '#6B7280',
    statusGhosted: '#EF4444',
    tagBackground: '#FFE5E5',
    tagText: '#F07A7A',
    pollBackground: '#F5F5F5',
    pollBar: '#F07A7A',
    pollBarBackground: '#E5E5E5',
    commentBackground: '#F8F9FA',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
  },
  dark: {
    text: '#f5f5f5',
    textSecondary: '#b0b0b0',
    background: '#121212',
    tint: tintColorDark,
    primary: '#F07A7A',
    secondary: '#3C2222',
    card: '#1e1e1e',
    border: '#333333',
    buttonText: '#ffffff',
    buttonDisabled: '#555555',
    icon: '#b0b0b0',
    tabIconDefault: '#b0b0b0',
    tabIconSelected: tintColorDark,
    statusActive: '#10B981',
    statusNew: '#3B82F6',
    statusFading: '#F59E0B',
    statusEnded: '#6B7280',
    statusGhosted: '#EF4444',
    tagBackground: '#3d2a2a',
    tagText: '#F07A7A',
    pollBackground: '#2a2a2a',
    pollBar: '#F07A7A',
    pollBarBackground: '#3d3d3d',
    commentBackground: '#2A2D31',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
  },
};
